name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci

    - name: Create .env file
      run: |
        touch .env
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
        echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" >> .env
        echo "MONGO_DB=${{ secrets.MONGO_DB }}" >> .env
        echo "MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "MONGO_DB_USERNAME=${{ secrets.MONGO_DB_USERNAME }}" >> .env
        echo "TWILIO_ACCOUNT_SID=${{ secrets.TWILIO_ACCOUNT_SID }}" >> .env
        echo "TWILIO_AUTH_TOKEN=${{ secrets.TWILIO_AUTH_TOKEN }}" >> .env
    - name: Install PM2 globally
      run: npm install -g pm2

    - name: Zip the application
      run: zip -r password-app-api.zip ./*

    - name: Deploy to AWS Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"  # Change if your Elastic Beanstalk is in a different region
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }} # Add this secret in your GitHub repository

      run: |
        # Upload the zipped application to S3
        aws s3 cp password-app-api.zip s3://${{ env.S3_BUCKET_NAME }}/password-app-api.zip
        
        # Create a new application version in Elastic Beanstalk
        aws elasticbeanstalk create-application-version \
          --application-name "password-api" \
          --version-label v1.0-${{ github.sha }} \
          --source-bundle S3Bucket=${{ env.S3_BUCKET_NAME }},S3Key=password-app-api.zip
        
        # Deploy the new version to the Elastic Beanstalk environment
        aws elasticbeanstalk update-environment \
          --environment-name "Password-api-env" \
          --version-label v1.0-${{ github.sha }}
